apiVersion: v1
kind: Secret
metadata:
  name: golder-staging-service-account-keys
  namespace: kamaji-system
  labels:
    app.kubernetes.io/name: kamaji
    app.kubernetes.io/component: pregenerated-certificates
    kamaji.clastix.io/cluster: golder-staging
    kamaji.clastix.io/certificate-type: service-account
type: Opaque
data:
  sa.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUGpCOVV6TWF4YXJLR0F6US8zNTN0cjhPMUxVVQpObFVLY0xsTnR0VEozdUdOL3Q5UDRXaitQYzJRb3lzQmRVejYyTGZSa0czNnJBU1V2SkFHNlhkSG93PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  sa.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1taHVubE9KTXZpVVU1Z2lUYUFjdUlJVjBrTHkyV2FFSTQ2MS9CWlpMbE5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUGpCOVV6TWF4YXJLR0F6US8zNTN0cjhPMUxVVU5sVUtjTGxOdHRUSjN1R04vdDlQNFdqKwpQYzJRb3lzQmRVejYyTGZSa0czNnJBU1V2SkFHNlhkSG93PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
