spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: '{{ .Values.kamajiService }}'
          namespace: '{{ .Values.kamajiNamespace }}'
          path: /convert
      conversionReviewVersions:
        - v1
