apiVersion: v1
kind: Secret
metadata:
  name: golder-secops-service-account-keys
  namespace: kamaji-system
  labels:
    app.kubernetes.io/name: kamaji
    app.kubernetes.io/component: pregenerated-certificates
    kamaji.clastix.io/cluster: golder-secops
    kamaji.clastix.io/certificate-type: service-account
type: Opaque
data:
  sa.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFR3l4WFJoM2ExcURFVmU5RW90T0ZxQXpqQmpRZQoyMSttaWNVWTVrSGtnVWNmNG93bDB1WEFyYmQwcWI1N1ZKdUI3ZE1qWVBUdUJNV3lrR0IraVdVL0p3PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  sa.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpxRWU0eTBsdE1kZS8zcldMTkNuTVkwY3d0eTNlNUlVUnJYdWJCNmdXQnpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFR3l4WFJoM2ExcURFVmU5RW90T0ZxQXpqQmpRZTIxK21pY1VZNWtIa2dVY2Y0b3dsMHVYQQpyYmQwcWI1N1ZKdUI3ZE1qWVBUdUJNV3lrR0IraVdVL0p3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
