apiVersion: v1
kind: Secret
metadata:
  name: golder-production-service-account-keys
  namespace: kamaji-system
  labels:
    app.kubernetes.io/name: kamaji
    app.kubernetes.io/component: pregenerated-certificates
    kamaji.clastix.io/cluster: golder-production
    kamaji.clastix.io/certificate-type: service-account
type: Opaque
data:
  sa.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbUFrYUZQaExpUzFzeHNhYmZlUVRCMVE3ZkJiRApKbU5SMjRaeGJ4c3czNEpMTy9FOGJvZWhmZWkxTWdHeGpwRU1nLzlCT2taVzVFOFd5V3ZvbnBBa2hnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  sa.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhXbXViYWF2d3RTaWVmN3QveGwvKy9hcm1sZWhrOUhyMktKcHZ0K2xNU1lvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbUFrYUZQaExpUzFzeHNhYmZlUVRCMVE3ZkJiREptTlIyNFp4YnhzdzM0SkxPL0U4Ym9laApmZWkxTWdHeGpwRU1nLzlCT2taVzVFOFd5V3ZvbnBBa2hnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
